### ISSUE TITLE
clean up resources page

### ISSUE THREAD

**Issue by rjb75** [RatikKapoor/ess-site#11]
add some CSS to make the resources page look better. Make featured resources look similar to featured boxes on booking page. Add icons to all resources.

**Comment by RatikKapoor** [comment]
It'll probably look good the chunks organized like cards, perhaps with a picture on the left. We could follow the "councils" or "teams" pages but just without hyperlinking.

**Comment by RatikKapoor** [comment]
Cleaned up and link items added
