### ISSUE TITLE
Fix "Coming Soon" Pages 

### ISSUE THREAD

**Issue by PixelPoncho** [RatikKapoor/ess-site#24]
Ultimately depends on the system and their monitor dimensions, however, at 100% zoom the size of the "Coming Soon" text prevents the usability of the navigation bar and the "Go Home" Button. 

![image](https://user-images.githubusercontent.com/33527005/92182514-1ef96a80-ee09-11ea-93ba-04a7459d81bf.png)
![image](https://user-images.githubusercontent.com/33527005/92182683-82839800-ee09-11ea-8c37-71b7751d0c28.png)

https://essucalgary.com/volunteer-hub/
https://essucalgary.com/projects-hub/

**Comment by RatikKapoor** [comment]
@rjb75 Can you reduce the font size to about 25% of what it is right now
