### ISSUE TITLE
Form Validation for Contact Us?

### ISSUE THREAD

**Issue by PixelPoncho** [RatikKapoor/ess-site#25]
Upon clicking "Send Message" with none of the text boxes filled in would expect some sort of prevention (i.e. "Required field") or in the very least no action to occur (i.e. prevent user interaction with the button till filled). However, at the current state the actual outcome is a 404 page?  

![submit](https://user-images.githubusercontent.com/33527005/92183532-f0c95a00-ee0b-11ea-9749-9e87f49fb21a.gif)

I didn't want to send actual content to not spam you guys, but I would recommend one of you guys testing it out, as has also been commented about in issue #4

**Comment by RatikKapoor** [comment]
Hi @PixelPoncho, don't worry about the spam. This website is a work in progress right now and we appreciate you going through it in detail finding things we may have missed. All issues should be closed within the next day or two.

**Comment by PixelPoncho** [comment]
@RatikKapoor So what you're saying is I should wait till next week to post any issues I find? :^)

**Comment by RatikKapoor** [comment]
@PixelPoncho haha not at all, please keep reporting issues. We've been staring at this site for so long we'll probably miss them if you don't. We appreciate your help here, thank you.
