### ISSUE TITLE
Typo on Departments Page

### ISSUE THREAD

**Issue by PixelPoncho** [RatikKapoor/ess-site#32]
Simple typo. CEUSS instead of CEUS!
![image](https://user-images.githubusercontent.com/33527005/92313895-1d0ce400-ef8e-11ea-9ec9-488041671096.png)

Wrong Name for Geo lol
![image](https://user-images.githubusercontent.com/33527005/92313935-a6bcb180-ef8e-11ea-9199-5eca3bceb6b1.png)

--- 
Also since we are discussing the Departments page, I'm wondering if the padding can be increased between all the logos and text, so that windows that aren't maximize don't result in overlap
![image](https://user-images.githubusercontent.com/33527005/92313918-62c9ac80-ef8e-11ea-94ed-6b262889a7e2.png)

**Comment by rjb75** [comment]
typo has been fixed

**Comment by PixelPoncho** [comment]
@rjb75 My mistake for not making it explicitly clear, however, the acronym of Civil Engineering Undergraduate Society is CEUS (as seen on their logo), not CEUSS
![image](https://user-images.githubusercontent.com/33527005/92316450-7b978980-efb1-11ea-9d69-b89cb43c9e68.png)

Additionally, the error with GESS still remains. GESS is short for Geomatics Engineering Students' Society not Civil Engineering Undergraduate Society
![image](https://user-images.githubusercontent.com/33527005/92316455-8a7e3c00-efb1-11ea-9fbe-5bedea2c4839.png)

**Comment by rjb75** [comment]
@PixelPoncho I got confused about that, sorry! It should be fixed now
